# Setup
title:               Eric Tang
tagline:             ''
description:         'Site for things'
url:                 http://erictang000.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eric Tang
  url:               https://twitter.com/erictang000
  email:             erictang000@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
